[package]
name = "native-ui-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native-ui-gnome = { git = "https://github.com/Surferlul/native-ui-gnome" }